Notifiy user is DAEMON is missing
Add a helpful message that the zuul binaries are missing from init.d
scripts.

Change-Id: I703b2c5cce3a09d0330063cb65097dc7041648bc
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

diff --git a/files/etc/init.d/zuul-merger b/files/etc/init.d/zuul-merger
--- a/files/etc/init.d/zuul-merger
+++ b/files/etc/init.d/zuul-merger
@@ -25,7 +25,10 @@ DAEMON=$PREFIX/bin/zuul-merger
 USER=${RUNASUSER:-zuul}
 
 # Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 5
+if ! [ -x "$DAEMON" ]; then
+    echo "$DAEMON: command not found"
+    exit 5
+fi
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
